# https://jekyllrb.com/docs/configuration/options/
# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
source:
  - index.html
include:
  - "(_)(\w)*(_)*.html"
  - "(_)(\w)*(_)*.*.html"
exlude:
  - README.md
  - README.PT.md
