# https://jekyllrb.com/docs/configuration/options/
# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
source: docs/
include: 
  - _*_.html
  - _*_.*.html

exclude:
  - README.md
  - README.PT.md
